services:
  db:
    image: postgres:16-alpine
    container_name: vlab_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: vlab_abastecimentos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cache:
    image: redis:7-alpine
    container_name: vlab_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    build: .
    container_name: vlab_api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache
    environment:
      - DATABASE_URL=postgresql+asyncpg://admin:adminpassword@db:5432/vlab_abastecimentos
      - REDIS_URL=redis://cache:6379
    volumes:
      - .:/app
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"

  
volumes:
  postgres_data:
  redis_data: