"""criar_tabela_abastecimentos

Revision ID: 171bbd225526
Revises:
Create Date: 2026-05-16 01:18:30.775765

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "171bbd225526"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "abastecimentos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_posto", sa.Integer(), nullable=False),
        sa.Column("data_hora", sa.DateTime(), nullable=False),
        sa.Column("tipo_combustivel", sa.String(), nullable=False),
        sa.Column("preco_por_litro", sa.Float(), nullable=False),
        sa.Column("volume_abastecido", sa.Float(), nullable=False),
        sa.Column("cpf_motorista", sa.String(length=14), nullable=False),
        sa.Column("dado_improprio", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_abastecimentos_id"), "abastecimentos", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_abastecimentos_id"), table_name="abastecimentos")
    op.drop_table("abastecimentos")
    # ### end Alembic commands ###
