"""alter_dado_improprio_to_not_null

Revision ID: 8a7a5f66535f
Revises: 171bbd225526
Create Date: 2026-05-16 17:55:59.559478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a7a5f66535f'
down_revision: Union[str, Sequence[str], None] = '171bbd225526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('abastecimentos', 'dado_improprio',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('abastecimentos', 'dado_improprio',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
